[2025-04-15T18:26:24.700+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T18:26:24.718+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_test manual__2025-04-15T16:15:18.938296+00:00 [queued]>
[2025-04-15T18:26:24.727+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_test manual__2025-04-15T16:15:18.938296+00:00 [queued]>
[2025-04-15T18:26:24.728+0200] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T18:26:24.738+0200] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_test> on 2025-04-15 16:15:18.938296+00:00
[2025-04-15T18:26:24.744+0200] {standard_task_runner.py:72} INFO - Started process 40093 to run task
[2025-04-15T18:26:24.753+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_pipeline', 'dbt_tasks.dbt_test', 'manual__2025-04-15T16:15:18.938296+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflke_airflow.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpj7n0xr5h']
[2025-04-15T18:26:24.755+0200] {standard_task_runner.py:105} INFO - Job 43: Subtask dbt_tasks.dbt_test
[2025-04-15T18:26:24.811+0200] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_test manual__2025-04-15T16:15:18.938296+00:00 [running]> on host macbook-pro-de-user.local
[2025-04-15T18:26:24.878+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_pipeline' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T16:15:18.938296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T16:15:18.938296+00:00'
[2025-04-15T18:26:24.880+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T18:26:24.881+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T18:26:24.881+0200] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_test state:running start_date:2025-04-15 16:26:24.719081+00:00
[2025-04-15T18:26:24.882+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline and current dag run status:running
[2025-04-15T18:26:24.883+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T18:26:24.884+0200] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2025-04-15T18:26:24.885+0200] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', '/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/bin/dbt test --project-dir /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake --select airflow']
[2025-04-15T18:26:24.894+0200] {subprocess.py:99} INFO - Output:
[2025-04-15T18:26:27.036+0200] {subprocess.py:106} INFO - [0m16:26:27  Running with dbt=1.9.4
[2025-04-15T18:26:28.085+0200] {subprocess.py:106} INFO - [0m16:26:28  Registered adapter: snowflake=1.9.2
[2025-04-15T18:26:28.610+0200] {subprocess.py:106} INFO - [0m16:26:28  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-15T18:26:28.612+0200] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-04-15T18:26:28.612+0200] {subprocess.py:106} INFO - - models.snowflake.example
[2025-04-15T18:26:28.851+0200] {subprocess.py:106} INFO - [0m16:26:28  Found 1 model, 2 data tests, 2 sources, 474 macros
[2025-04-15T18:26:28.853+0200] {subprocess.py:106} INFO - [0m16:26:28
[2025-04-15T18:26:28.854+0200] {subprocess.py:106} INFO - [0m16:26:28  Concurrency: 1 threads (target='dev')
[2025-04-15T18:26:28.855+0200] {subprocess.py:106} INFO - [0m16:26:28
[2025-04-15T18:26:29.546+0200] {subprocess.py:106} INFO - [0m16:26:29  1 of 2 START test source_not_null_snowflake_staging_orders_ordernumber ......... [RUN]
[2025-04-15T18:26:29.751+0200] {subprocess.py:106} INFO - [0m16:26:29  1 of 2 PASS source_not_null_snowflake_staging_orders_ordernumber ............... [[32mPASS[0m in 0.20s]
[2025-04-15T18:26:29.755+0200] {subprocess.py:106} INFO - [0m16:26:29  2 of 2 START test source_unique_snowflake_staging_orders_ordernumber ........... [RUN]
[2025-04-15T18:26:29.837+0200] {subprocess.py:106} INFO - [0m16:26:29  2 of 2 PASS source_unique_snowflake_staging_orders_ordernumber ................. [[32mPASS[0m in 0.08s]
[2025-04-15T18:26:29.892+0200] {subprocess.py:106} INFO - [0m16:26:29
[2025-04-15T18:26:29.894+0200] {subprocess.py:106} INFO - [0m16:26:29  Finished running 2 data tests in 0 hours 0 minutes and 1.04 seconds (1.04s).
[2025-04-15T18:26:29.939+0200] {subprocess.py:106} INFO - [0m16:26:29
[2025-04-15T18:26:29.940+0200] {subprocess.py:106} INFO - [0m16:26:29  [32mCompleted successfully[0m
[2025-04-15T18:26:29.941+0200] {subprocess.py:106} INFO - [0m16:26:29
[2025-04-15T18:26:29.942+0200] {subprocess.py:106} INFO - [0m16:26:29  Done. PASS=2 WARN=0 ERROR=0 SKIP=0 TOTAL=2
[2025-04-15T18:26:30.721+0200] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-15T18:26:30.738+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T18:26:30.740+0200] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_snowflake_pipeline, task_id=dbt_tasks.dbt_test, run_id=manual__2025-04-15T16:15:18.938296+00:00, execution_date=20250415T161518, start_date=20250415T162624, end_date=20250415T162630
[2025-04-15T18:26:30.754+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-15T18:26:30.755+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-15T18:26:30.755+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline queued_at:2025-04-15 16:15:18.990957+00:00
[2025-04-15T18:26:30.756+0200] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-de-user.local operator:BashOperator
[2025-04-15T18:26:30.781+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T18:26:30.798+0200] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T18:26:30.798+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
