[2025-04-15T18:20:39.639+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T18:20:39.655+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T16:15:18.938296+00:00 [queued]>
[2025-04-15T18:20:39.663+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T16:15:18.938296+00:00 [queued]>
[2025-04-15T18:20:39.664+0200] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-15T18:20:39.680+0200] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_debug> on 2025-04-15 16:15:18.938296+00:00
[2025-04-15T18:20:39.687+0200] {standard_task_runner.py:72} INFO - Started process 32393 to run task
[2025-04-15T18:20:39.695+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_pipeline', 'dbt_tasks.dbt_debug', 'manual__2025-04-15T16:15:18.938296+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflke_airflow.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpxpsqw3uh']
[2025-04-15T18:20:39.699+0200] {standard_task_runner.py:105} INFO - Job 35: Subtask dbt_tasks.dbt_debug
[2025-04-15T18:20:39.764+0200] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T16:15:18.938296+00:00 [running]> on host macbook-pro-de-user.local
[2025-04-15T18:20:39.824+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_pipeline' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T16:15:18.938296+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T16:15:18.938296+00:00'
[2025-04-15T18:20:39.827+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T18:20:39.828+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T18:20:39.829+0200] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_debug state:running start_date:2025-04-15 16:20:39.655784+00:00
[2025-04-15T18:20:39.830+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline and current dag run status:running
[2025-04-15T18:20:39.830+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T18:20:39.832+0200] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2025-04-15T18:20:39.833+0200] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', '/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/bin/dbt debug --project-dir /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake']
[2025-04-15T18:20:39.841+0200] {subprocess.py:99} INFO - Output:
[2025-04-15T18:20:42.618+0200] {subprocess.py:106} INFO - [0m16:20:42  Running with dbt=1.9.4
[2025-04-15T18:20:42.640+0200] {subprocess.py:106} INFO - [0m16:20:42  dbt version: 1.9.4
[2025-04-15T18:20:42.641+0200] {subprocess.py:106} INFO - [0m16:20:42  python version: 3.11.11
[2025-04-15T18:20:42.642+0200] {subprocess.py:106} INFO - [0m16:20:42  python path: /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/bin/python
[2025-04-15T18:20:42.642+0200] {subprocess.py:106} INFO - [0m16:20:42  os info: macOS-15.3.2-x86_64-i386-64bit
[2025-04-15T18:20:43.719+0200] {subprocess.py:106} INFO - [0m16:20:43  Using profiles dir at /Users/user/.dbt
[2025-04-15T18:20:43.720+0200] {subprocess.py:106} INFO - [0m16:20:43  Using profiles.yml file at /Users/user/.dbt/profiles.yml
[2025-04-15T18:20:43.721+0200] {subprocess.py:106} INFO - [0m16:20:43  Using dbt_project.yml file at /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake/dbt_project.yml
[2025-04-15T18:20:43.722+0200] {subprocess.py:106} INFO - [0m16:20:43  adapter type: snowflake
[2025-04-15T18:20:43.723+0200] {subprocess.py:106} INFO - [0m16:20:43  adapter version: 1.9.2
[2025-04-15T18:20:43.925+0200] {subprocess.py:106} INFO - [0m16:20:43  Configuration:
[2025-04-15T18:20:43.926+0200] {subprocess.py:106} INFO - [0m16:20:43    profiles.yml file [[32mOK found and valid[0m]
[2025-04-15T18:20:43.927+0200] {subprocess.py:106} INFO - [0m16:20:43    dbt_project.yml file [[32mOK found and valid[0m]
[2025-04-15T18:20:43.929+0200] {subprocess.py:106} INFO - [0m16:20:43  Required dependencies:
[2025-04-15T18:20:43.994+0200] {subprocess.py:106} INFO - [0m16:20:43   - git [[32mOK found[0m]
[2025-04-15T18:20:43.995+0200] {subprocess.py:106} INFO - 
[2025-04-15T18:20:43.997+0200] {subprocess.py:106} INFO - [0m16:20:43  Connection:
[2025-04-15T18:20:43.998+0200] {subprocess.py:106} INFO - [0m16:20:43    account: dbjbmjn-gb63301
[2025-04-15T18:20:43.999+0200] {subprocess.py:106} INFO - [0m16:20:43    user: AIDASOW73
[2025-04-15T18:20:44.000+0200] {subprocess.py:106} INFO - [0m16:20:43    database: dbt_demo
[2025-04-15T18:20:44.001+0200] {subprocess.py:106} INFO - [0m16:20:43    warehouse: compute_wh
[2025-04-15T18:20:44.002+0200] {subprocess.py:106} INFO - [0m16:20:43    role: accountadmin
[2025-04-15T18:20:44.003+0200] {subprocess.py:106} INFO - [0m16:20:44    schema: base
[2025-04-15T18:20:44.004+0200] {subprocess.py:106} INFO - [0m16:20:44    authenticator: None
[2025-04-15T18:20:44.005+0200] {subprocess.py:106} INFO - [0m16:20:44    oauth_client_id: None
[2025-04-15T18:20:44.006+0200] {subprocess.py:106} INFO - [0m16:20:44    query_tag: None
[2025-04-15T18:20:44.007+0200] {subprocess.py:106} INFO - [0m16:20:44    client_session_keep_alive: False
[2025-04-15T18:20:44.008+0200] {subprocess.py:106} INFO - [0m16:20:44    host: None
[2025-04-15T18:20:44.008+0200] {subprocess.py:106} INFO - [0m16:20:44    port: None
[2025-04-15T18:20:44.009+0200] {subprocess.py:106} INFO - [0m16:20:44    proxy_host: None
[2025-04-15T18:20:44.010+0200] {subprocess.py:106} INFO - [0m16:20:44    proxy_port: None
[2025-04-15T18:20:44.011+0200] {subprocess.py:106} INFO - [0m16:20:44    protocol: None
[2025-04-15T18:20:44.012+0200] {subprocess.py:106} INFO - [0m16:20:44    connect_retries: 1
[2025-04-15T18:20:44.013+0200] {subprocess.py:106} INFO - [0m16:20:44    connect_timeout: None
[2025-04-15T18:20:44.014+0200] {subprocess.py:106} INFO - [0m16:20:44    retry_on_database_errors: False
[2025-04-15T18:20:44.015+0200] {subprocess.py:106} INFO - [0m16:20:44    retry_all: False
[2025-04-15T18:20:44.016+0200] {subprocess.py:106} INFO - [0m16:20:44    insecure_mode: False
[2025-04-15T18:20:44.017+0200] {subprocess.py:106} INFO - [0m16:20:44    reuse_connections: True
[2025-04-15T18:20:44.018+0200] {subprocess.py:106} INFO - [0m16:20:44  Registered adapter: snowflake=1.9.2
[2025-04-15T18:20:45.200+0200] {subprocess.py:106} INFO - [0m16:20:45    Connection test: [[32mOK connection ok[0m]
[2025-04-15T18:20:45.201+0200] {subprocess.py:106} INFO - 
[2025-04-15T18:20:45.203+0200] {subprocess.py:106} INFO - [0m16:20:45  [32mAll checks passed![0m
[2025-04-15T18:20:46.139+0200] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-15T18:20:46.174+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T18:20:46.176+0200] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_snowflake_pipeline, task_id=dbt_tasks.dbt_debug, run_id=manual__2025-04-15T16:15:18.938296+00:00, execution_date=20250415T161518, start_date=20250415T162039, end_date=20250415T162046
[2025-04-15T18:20:46.195+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-15T18:20:46.196+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-15T18:20:46.196+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline queued_at:2025-04-15 16:15:18.990957+00:00
[2025-04-15T18:20:46.197+0200] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-de-user.local operator:BashOperator
[2025-04-15T18:20:46.220+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T18:20:46.256+0200] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-15T18:20:46.258+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
