[2025-04-15T20:14:42.825+0200] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T20:14:42.837+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T18:14:35.865819+00:00 [queued]>
[2025-04-15T20:14:42.844+0200] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T18:14:35.865819+00:00 [queued]>
[2025-04-15T20:14:42.845+0200] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-15T20:14:42.856+0200] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_tasks.dbt_debug> on 2025-04-15 18:14:35.865819+00:00
[2025-04-15T20:14:42.862+0200] {standard_task_runner.py:72} INFO - Started process 84422 to run task
[2025-04-15T20:14:42.869+0200] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_snowflake_pipeline', 'dbt_tasks.dbt_debug', 'manual__2025-04-15T18:14:35.865819+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dbt_snowflke_airflow.py', '--cfg-path', '/var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T/tmpkn43n10k']
[2025-04-15T20:14:42.872+0200] {standard_task_runner.py:105} INFO - Job 44: Subtask dbt_tasks.dbt_debug
[2025-04-15T20:14:42.921+0200] {task_command.py:467} INFO - Running <TaskInstance: dbt_snowflake_pipeline.dbt_tasks.dbt_debug manual__2025-04-15T18:14:35.865819+00:00 [running]> on host macbook-pro-de-user.local
[2025-04-15T20:14:42.981+0200] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_snowflake_pipeline' AIRFLOW_CTX_TASK_ID='dbt_tasks.dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T18:14:35.865819+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T18:14:35.865819+00:00'
[2025-04-15T20:14:42.983+0200] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-15T20:14:42.983+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-15T20:14:42.984+0200] {logging_mixin.py:190} INFO - Current task name:dbt_tasks.dbt_debug state:running start_date:2025-04-15 18:14:42.837462+00:00
[2025-04-15T20:14:42.984+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline and current dag run status:running
[2025-04-15T20:14:42.985+0200] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T20:14:42.989+0200] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/gn/cr4yj18d1tv34pkws9v_kq1r0000gn/T
[2025-04-15T20:14:42.990+0200] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', '/Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/bin/dbt debug --project-dir /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake']
[2025-04-15T20:14:43.000+0200] {subprocess.py:99} INFO - Output:
[2025-04-15T20:14:45.738+0200] {subprocess.py:106} INFO - [0m18:14:45  Running with dbt=1.9.4
[2025-04-15T20:14:45.775+0200] {subprocess.py:106} INFO - [0m18:14:45  dbt version: 1.9.4
[2025-04-15T20:14:45.776+0200] {subprocess.py:106} INFO - [0m18:14:45  python version: 3.11.11
[2025-04-15T20:14:45.777+0200] {subprocess.py:106} INFO - [0m18:14:45  python path: /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/airflow-env/bin/python
[2025-04-15T20:14:45.778+0200] {subprocess.py:106} INFO - [0m18:14:45  os info: macOS-15.3.2-x86_64-i386-64bit
[2025-04-15T20:14:46.786+0200] {subprocess.py:106} INFO - [0m18:14:46  Using profiles dir at /Users/user/.dbt
[2025-04-15T20:14:46.787+0200] {subprocess.py:106} INFO - [0m18:14:46  Using profiles.yml file at /Users/user/.dbt/profiles.yml
[2025-04-15T20:14:46.787+0200] {subprocess.py:106} INFO - [0m18:14:46  Using dbt_project.yml file at /Users/user/Documents/learningProg/dataengineering/de_dbt_snowflake_airflow/snowflake/dbt_project.yml
[2025-04-15T20:14:46.788+0200] {subprocess.py:106} INFO - [0m18:14:46  adapter type: snowflake
[2025-04-15T20:14:46.788+0200] {subprocess.py:106} INFO - [0m18:14:46  adapter version: 1.9.2
[2025-04-15T20:14:46.947+0200] {subprocess.py:106} INFO - [0m18:14:46  Configuration:
[2025-04-15T20:14:46.948+0200] {subprocess.py:106} INFO - [0m18:14:46    profiles.yml file [[32mOK found and valid[0m]
[2025-04-15T20:14:46.949+0200] {subprocess.py:106} INFO - [0m18:14:46    dbt_project.yml file [[32mOK found and valid[0m]
[2025-04-15T20:14:46.949+0200] {subprocess.py:106} INFO - [0m18:14:46  Required dependencies:
[2025-04-15T20:14:47.039+0200] {subprocess.py:106} INFO - [0m18:14:47   - git [[32mOK found[0m]
[2025-04-15T20:14:47.040+0200] {subprocess.py:106} INFO - 
[2025-04-15T20:14:47.041+0200] {subprocess.py:106} INFO - [0m18:14:47  Connection:
[2025-04-15T20:14:47.042+0200] {subprocess.py:106} INFO - [0m18:14:47    account: dbjbmjn-gb63301
[2025-04-15T20:14:47.043+0200] {subprocess.py:106} INFO - [0m18:14:47    user: AIDASOW73
[2025-04-15T20:14:47.044+0200] {subprocess.py:106} INFO - [0m18:14:47    database: dbt_demo
[2025-04-15T20:14:47.045+0200] {subprocess.py:106} INFO - [0m18:14:47    warehouse: compute_wh
[2025-04-15T20:14:47.046+0200] {subprocess.py:106} INFO - [0m18:14:47    role: accountadmin
[2025-04-15T20:14:47.047+0200] {subprocess.py:106} INFO - [0m18:14:47    schema: base
[2025-04-15T20:14:47.048+0200] {subprocess.py:106} INFO - [0m18:14:47    authenticator: None
[2025-04-15T20:14:47.049+0200] {subprocess.py:106} INFO - [0m18:14:47    oauth_client_id: None
[2025-04-15T20:14:47.050+0200] {subprocess.py:106} INFO - [0m18:14:47    query_tag: None
[2025-04-15T20:14:47.051+0200] {subprocess.py:106} INFO - [0m18:14:47    client_session_keep_alive: False
[2025-04-15T20:14:47.052+0200] {subprocess.py:106} INFO - [0m18:14:47    host: None
[2025-04-15T20:14:47.053+0200] {subprocess.py:106} INFO - [0m18:14:47    port: None
[2025-04-15T20:14:47.054+0200] {subprocess.py:106} INFO - [0m18:14:47    proxy_host: None
[2025-04-15T20:14:47.055+0200] {subprocess.py:106} INFO - [0m18:14:47    proxy_port: None
[2025-04-15T20:14:47.056+0200] {subprocess.py:106} INFO - [0m18:14:47    protocol: None
[2025-04-15T20:14:47.057+0200] {subprocess.py:106} INFO - [0m18:14:47    connect_retries: 1
[2025-04-15T20:14:47.058+0200] {subprocess.py:106} INFO - [0m18:14:47    connect_timeout: None
[2025-04-15T20:14:47.059+0200] {subprocess.py:106} INFO - [0m18:14:47    retry_on_database_errors: False
[2025-04-15T20:14:47.060+0200] {subprocess.py:106} INFO - [0m18:14:47    retry_all: False
[2025-04-15T20:14:47.061+0200] {subprocess.py:106} INFO - [0m18:14:47    insecure_mode: False
[2025-04-15T20:14:47.062+0200] {subprocess.py:106} INFO - [0m18:14:47    reuse_connections: True
[2025-04-15T20:14:47.063+0200] {subprocess.py:106} INFO - [0m18:14:47  Registered adapter: snowflake=1.9.2
[2025-04-15T20:14:48.132+0200] {subprocess.py:106} INFO - [0m18:14:48    Connection test: [[32mOK connection ok[0m]
[2025-04-15T20:14:48.149+0200] {subprocess.py:106} INFO - 
[2025-04-15T20:14:48.184+0200] {subprocess.py:106} INFO - [0m18:14:48  [32mAll checks passed![0m
[2025-04-15T20:14:49.208+0200] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-15T20:14:49.327+0200] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T20:14:49.352+0200] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_snowflake_pipeline, task_id=dbt_tasks.dbt_debug, run_id=manual__2025-04-15T18:14:35.865819+00:00, execution_date=20250415T181435, start_date=20250415T181442, end_date=20250415T181449
[2025-04-15T20:14:49.493+0200] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-15T20:14:49.512+0200] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-15T20:14:49.532+0200] {logging_mixin.py:190} INFO - Dag name:dbt_snowflake_pipeline queued_at:2025-04-15 18:14:35.935400+00:00
[2025-04-15T20:14:49.552+0200] {logging_mixin.py:190} INFO - Task hostname:macbook-pro-de-user.local operator:BashOperator
[2025-04-15T20:14:49.597+0200] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-15T20:14:49.642+0200] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-15T20:14:49.644+0200] {local_task_job_runner.py:245} INFO - ::endgroup::
